version: '3.8'

services:
  app:
    image: patientor-front_dev
    build:
      context: ./patientor
      dockerfile: dev.Dockerfile
    volumes:
      - ./patientor:/usr/src/app
    environment:
      - WATCHPACK_POLLING=true
      - WDS_SOCKET_HOST=127.0.0.1
      - WDS_SOCKET_PORT=8080
    container_name: todo-front_dev
  
  server:
    image: patientor-back_dev
    build:
      context: ./patientor_backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./patientor_backend:/usr/src/app
    container_name: patientor-back_dev

  nginx:
    image: nginx:1.27.0
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
      - server