POST http://localhost:3000/api/patients HTTP/1.1
content-type: application/json

{
  "name": "requestTest",
  "dateOfBirth": "2002-10-10",
  "ssn": "101002-112a",
  "gender": "male",
  "occupation": "tester",
  "entries": []
}