version: '3.8'

services:
  # app:
  #   build: .
  #   ports:
  #     - "3000:3000"  # Map container port 3000 to host port 3000
  #   depends_on:
  #     - mongo
  #     - redis
  #   environment:
  #     NODE_ENV: development
  #     REDIS_URL: redis://redis:6379  # Reference to the redis service within Docker Compose
  #     MONGO_URL: mongodb://the_username:the_password@mongodb:3456/the_database  # Reference to the mongo service within Docker Compose
  #   command: ['npm', 'run', 'dev'] 

  # app:
  #   image: todo-backend-dev
  #   build:
  #     context: . # The context will pick this directory as the "build context"
  #     dockerfile: dev.Dockerfile # This will simply tell which dockerfile to read
  #   volumes:
  #     - ./:/usr/src/app/backend # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - mongo
  #     - redis
  #   environment:
  #     NODE_ENV: development
  #     REDIS_URL: redis://redis:6379  # Reference to the redis service within Docker Compose
  #     MONGO_URL: mongodb://the_username:the_password@localhost:3456/the_database  # Reference to the mongo service within Docker Compose
  #   command: ['npm', 'run', 'dev'] 
  #   container_name: todo-backend-dev # This will name the container hello-front-dev
version: "3.8"

networks:
  my_network:
    driver: bridge

services:
  mongo:
    image: mongo:latest
    networks:
      - my_network

    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: the_username
      MONGO_INITDB_ROOT_PASSWORD: the_password
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    networks:
      - my_network
    volumes:
      - redis-data:/data

  web:
    build: .
    depends_on:
      - mongo
      - redis
    networks:
      - my_network
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://the_username:the_password@localhost:3456/the_database

volumes:
  mongo-data:
  redis-data:
